Fixed calculate a sidePage height when it comes as standalone
linuxmint/cinnamon pull request #11900
Opened 2023-10-23 22:21 UTC by kacperpaczos

All modules, when called as standalone (via menu), were too small (in height). I added the missing variables and called the calculus function in this case.
Before:
![image](https://github.com/linuxmint/cinnamon/assets/23406555/9c970294-05ca-4c9a-84b3-4945ab79f96c)

After:
![image](https://github.com/linuxmint/cinnamon/assets/23406555/0e0c8786-ad55-4336-8fad-3faa213418c2)

2023-10-24 20:35 UTC, claudiux commented
@kacperpaczos Please check above review.

2023-10-24 21:13 UTC, kacperpaczos commented
> @kacperpaczos Please check above review.

I am sorry, but i don't understand.

2023-10-24 22:20 UTC, claudiux commented
The ' + WIN_H_PADDING' line 240 adds useless space at the bottom of the window.

2023-10-25 01:53 UTC, claudiux requested changes

2023-10-25 21:46 UTC, kacperpaczos reviewed
lgtm

2023-10-26 00:04 UTC, claudiux approved these changes

2023-10-26 00:05 UTC, merged