Update cs_screensaver to handle new Weather widget
linuxmint/cinnamon pull request #12516
Opened 2024-11-22 08:54 UTC by queenkjuul

These changes are necessary to enable the Screensaver Weather widget as proposed here:

https://github.com/linuxmint/cinnamon-screensaver/pull/464

I have relocated the "Away Message" controls from the Customize page to the Settings page, as the additional Weather fields on the Customize page caused the window to be too tall by default. I thought Away Message was the most "settings-like" of the Customize page options. 

Schema updates are made in cinnamon-desktop here:

https://github.com/linuxmint/cinnamon-desktop/pull/246
![Screenshot from 2024-11-22 02-54-07](https://github.com/user-attachments/assets/2db85e6d-3921-4dc1-8e5a-3ef1dbf96f53)

![Screenshot from 2024-11-22 02-54-32](https://github.com/user-attachments/assets/0b3cbf35-fafc-4cb2-be7e-0e07b7177da2)

2024-12-08 21:34 UTC, A1exKH requested changes
Please resolve conflicts for this brunch.

2025-02-20 03:38 UTC, queenkjuul commented
@A1exKH sorry, completely lost track of this; updated

2025-11-19 16:28 UTC, mtwebster commented
Please remove the potfile changes, that is done by the maintainers.

We don't want the vscode file either.

2025-12-15 01:37 UTC, queenkjuul commented
> Please remove the potfile changes, that is done by the maintainers.
> 
> We don't want the vscode file either.

fixed

2026-08-27 13:12 UTC, mtwebster commented
See comment in https://github.com/linuxmint/cinnamon-screensaver/pull/464

2026-08-27 13:12 UTC, closed without merging